Added module on damage analysis for Eearthquakes
hotosm/toolbox pull request #16
Opened 2023-03-22 18:29 UTC by Claurt07

Added module developed by Honey on damage analysis for Earthquakes as module 7.4 (only in English)

2023-03-27 18:41 UTC, dakotabenjamin approved these changes

2023-03-27 18:41 UTC, dakotabenjamin commented on content/en/pages/data-use-and-analysis/7.5-OSM-Analytics
It looks like this file was never registered in the menu- could you add `.md` to the end of it? and rename the header as well

2023-03-27 18:41 UTC, dakotabenjamin commented on static/images/data-use-and-analysis/fig1_damage_analysis.jpeg
Not a blocker for this PR to be merged- but these days for web-served content, .webp or .png are preferred formats.

2023-03-27 19:13 UTC, emi420 commented on static/images/data-use-and-analysis/fig1_damage_analysis.jpeg
@Claurt07 Screenshots will look much better if you use PNG :)

JPEG are better for digital photos and PNG for web graphics.

2023-03-28 13:25 UTC, emi420 requested changes
Hey @Claurt07 could you change images from JPEG for PNG, add .md to `content/en/pages/data-use-and-analysis/7.5-OSM-Analytics` and rename the header? thanks!

2023-03-28 14:28 UTC, Claurt07 commented on static/images/data-use-and-analysis/fig1_damage_analysis.jpeg
I was trying to use PNG, only JPEG would load/render. As I had to release this ASAP I did not explore why PNG was not loading (if you check all the other files are either JPEG or GIF). 
For future ones I will explore how to use PNG instead

2023-03-28 14:33 UTC, Claurt07 commented on content/en/pages/data-use-and-analysis/7.5-OSM-Analytics
This document was already there, so I did not delete, only changed the number from 7.4 to 7.4 so the new module would take its place. As it seems its incomplete I did not change it to register on the menu.

2023-03-28 14:37 UTC, Claurt07 commented
Hey, @emi420 just echoing the above comments:
- I tried using PNG, but only JPEG would load/render.  All the other files are either JPEG or GIF.
- This document was already there, so I did not delete it, I only changed the number from 7.4 to 7.4 so the new module would take its place. As it seems incomplete, I did not change it to register on the menu.

2023-03-29 11:37 UTC, merged